const fs = require('fs'), path = require('path'), assert = require('assert/strict');
const {createPoseTools, quaternion} = require('../../shared/motion_pose');
const workspace = path.resolve(__dirname, '..'), root = path.resolve(workspace, '../..');
const read = name => JSON.parse(fs.readFileSync(path.join(root, name), 'utf8'));
const current = read('models/promised_consort/animations/promised_consort.animation.json').animations;
const report = read('models/promised_consort/aerial_presence_validation.json');
const baselinePath = path.join(root, 'build/motion-review/before.json');
assert(fs.existsSync(baselinePath), 'Comparison requires the pre-edit samples generated by refine_aerial_presence.js');
const before = JSON.parse(fs.readFileSync(baselinePath, 'utf8')).animations;
const {poseAt, point} = createPoseTools(read('models/promised_consort/rig.json'));
const joints = ['body','chest','head','upper_arm_r','forearm_r','upper_arm_l','forearm_l','thigh_r','shin_r','foot_r','thigh_l','shin_l','foot_l'];
const angle = (a,b) => 2*Math.acos(Math.min(1,Math.abs(quaternion(a).dot(quaternion(b)))))*180/Math.PI;
let checks = 0;
const measurements=[];
for (const entry of report.changed_clips) {
    const name = 'animation.promised_consort.'+entry.name, old = before[name], clip = current[name], duration=clip.animation_length*20;
    assert.equal(duration,old.animation_length*20);
    let maximumContactError=0, maximumGroundedFootError=0, maximumHalfTickJointChange=0, maximumOldHalfTickJointChange=0;
    for(const t of entry.contacts) for(const side of ['r','l']) {
        const difference=point(poseAt(clip,t),'blade_tip_'+side).distanceTo(point(poseAt(old,t),'blade_tip_'+side));
        maximumContactError=Math.max(maximumContactError,difference); assert(difference<0.001,name+' contact changed'); checks++;
    }
    for(let t=0;t<=duration;t+=0.0625) {
        const pose=poseAt(clip,t), prior=poseAt(clip,Math.max(0,t-0.5)), original=poseAt(old,t), oldPrior=poseAt(old,Math.max(0,t-0.5));
        for(const bone of joints) {
            const step=angle(prior[bone].rotation,pose[bone].rotation), oldStep=angle(oldPrior[bone].rotation,original[bone].rotation);
            maximumHalfTickJointChange=Math.max(maximumHalfTickJointChange,step);
            maximumOldHalfTickJointChange=Math.max(maximumOldHalfTickJointChange,oldStep);
            assert(step<=Math.max(65,oldStep+3), name+'/'+bone+' interpolation spike at '+t+': '+step+' vs '+oldStep); checks++;
        }
        const airborne = entry.name==='promised_consort' && t>=83 && t<=111
            || entry.name==='lightspeed_slash' && t>=8 && t<=69
            || entry.name==='lightspeed_side_dash' && t>=8 && t<=24;
        if(!airborne) for(const side of ['r','l']) {
            const difference=point(pose,'foot_'+side).distanceTo(point(original,'foot_'+side));
            maximumGroundedFootError=Math.max(maximumGroundedFootError,difference);
            assert(difference<0.08,name+' planted foot moved at '+t+': '+difference); checks++;
        }
    }
    measurements.push({name:entry.name,maximumContactError,maximumGroundedFootError,maximumHalfTickJointChange,maximumOldHalfTickJointChange});
}
const result={checks,sample_interval_ticks:0.0625,measurements,source:'Serialized runtime clips compared to pre-edit pose samples; not a world test'};
if(process.argv.includes('--record')) {report.interpolation_validation=result;fs.writeFileSync(path.join(workspace,'aerial_presence_validation.json'),JSON.stringify(report,null,2)+'\n');}
console.log(JSON.stringify(result));
