modLoader = "javafml"
loaderVersion = "${loaderVersion}"
license = "${license}"

[[mods]]
modId = "${id}"
version = "${version}"
displayName = "${name}"
authors = "${authors}"
description = '''${description}'''

[[mixins]]
config = "${id}.mixins.json"

[[dependencies.elder_bosses]]
modId = "neoforge"
type = "required"
versionRange = "${neoForgeVersionRange}"
ordering = "NONE"
side = "BOTH"

[[dependencies.elder_bosses]]
modId = "minecraft"
type = "required"
versionRange = "${minecraftVersionRange}"
ordering = "NONE"
side = "BOTH"